project_name = "toast"

[tasks]
build = "cargo build"
install = "cargo install --locked --path ."
fmt = "cargo +nightly fmt"
fix = [
  "cargo clippy --fix --allow-dirty",
  "cargo +nightly fmt",
]

[packages]
rust = "nightly"
